//! Types for documentation purposes in the KSY

use indexmap::IndexMap;
use serde::{Deserialize, Serialize};

use crate::identifiers::{Iso, Loc, MediaWiki, MimeType, Pronom, Rfc, Wikidata};
use crate::parser::{OneOrMany, Scalar};

/// Documentation for types, parameters, enum values and attributes.
#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub struct Doc {
  /// Used to give a more detailed description of a user-defined type.
  /// In most languages, it will be used as a docstring compatible with
  /// tools like Javadoc, Doxygen, JSDoc, etc.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub doc: Option<String>,
  /// Used to provide reference to original documentation (if the ksy file
  /// is actually an implementation of some documented format).
  ///
  /// Contains:
  /// 1. URL as text,
  /// 2. arbitrary string, or
  /// 3. URL as text + space + arbitrary string
  #[serde(skip_serializing_if = "Option::is_none")]
  pub doc_ref: Option<DocRef>,
}

/// List of references to original documentation.
pub type DocRef = OneOrMany<String>; //TODO: enum { Url, Text, UrlAndText }
/// List of references to arbitrary documentation in various knowledge bases.
pub type XRef = OneOrMany<Scalar>;

/// Collections of references in various knowledge bases.
#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
pub struct XRefs {
  /// Article name at [Forensics Wiki][wiki], which is a CC-BY-SA-licensed wiki with
  /// information on digital forensics, file formats and tools.
  ///
  /// Full link name could be generated as `https://forensicswiki.xyz/page/` + this value
  ///
  /// [wiki]: https://forensicswiki.xyz/page/Main_Page
  #[serde(skip_serializing_if = "Option::is_none")]
  pub forensicswiki: Option<OneOrMany<MediaWiki>>,
  /// ISO/IEC standard number, reference to a standard accepted and published by
  /// [ISO] (International Organization for Standardization).
  ///
  /// ISO standards typically have clear designations like "ISO/IEC 15948:2004",
  /// so value should be citing everything except for "ISO/IEC", i.e. `15948:2004`
  ///
  /// [ISO]: https://www.iso.org/
  #[serde(skip_serializing_if = "Option::is_none")]
  pub iso: Option<OneOrMany<Iso>>,
  /// Article name at ["Just Solve the File Format Problem" wiki][wiki], a wiki that
  /// collects information on many file formats.
  ///
  /// Full link name could be generated as `http://fileformats.archiveteam.org/wiki/` + this value
  ///
  /// [wiki]: http://fileformats.archiveteam.org/wiki/Main_Page
  #[serde(skip_serializing_if = "Option::is_none")]
  pub justsolve: Option<OneOrMany<MediaWiki>>,
  /// Identifier in [Digital Formats][formats] database of [US Library of Congress][loc].
  ///
  /// Value typically looks like `fddXXXXXX`, where `XXXXXX` is a 6-digit identifier.
  ///
  /// [formats]: https://www.loc.gov/preservation/digital/formats/fdd/browse_list.shtml
  /// [loc]: https://www.loc.gov/
  #[serde(skip_serializing_if = "Option::is_none")]
  pub loc: Option<OneOrMany<Loc>>,
  /// MIME type (IANA media type), a string typically used in various Internet protocols
  /// to specify format of binary payload.
  ///
  /// There is a [central registry of media types][registry] managed by IANA.
  ///
  /// Value must specify full MIME type (both parts), e.g. `image/png`.
  ///
  /// [registry]: https://www.iana.org/assignments/media-types/media-types.xhtml
  #[serde(skip_serializing_if = "Option::is_none")]
  pub mime: Option<OneOrMany<MimeType>>,
  /// Format identifier in [PRONOM Technical Registry][registry] of
  /// [UK National Archives][archives], which is a massive file formats database
  /// that catalogues many file formats for digital preservation purposes.
  ///
  /// [registry]: https://www.nationalarchives.gov.uk/PRONOM/Default.aspx
  /// [archives]: https://www.nationalarchives.gov.uk/
  #[serde(skip_serializing_if = "Option::is_none")]
  pub pronom: Option<OneOrMany<Pronom>>,
  /// Reference to [RFC](https://en.wikipedia.org/wiki/Request_for_Comments),
  /// "Request for Comments" documents maintained by ISOC (Internet Society).
  ///
  /// RFCs are typically treated as global, Internet-wide standards, and,
  /// for example, many networking / interoperability protocols are specified in RFCs.
  ///
  /// Value should be just raw RFC number, without any prefixes, e.g. `1234`
  #[serde(skip_serializing_if = "Option::is_none")]
  pub rfc: Option<OneOrMany<Rfc>>,
  /// Item identifier at Wikidata, a global knowledge base.
  ///
  /// Value typically follows `Qxxx` pattern, where `xxx` is a number
  /// generated by Wikidata, e.g. `Q535473`.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub wikidata: Option<OneOrMany<Wikidata>>,

  /// References to any other formats.
  #[serde(flatten)]
  pub other: IndexMap<String, XRef>,
}

////////////////////////////////////////////////////////////////////////////////////////////////////

#[test]
fn doc_ref() {
  use crate::parser::Attribute;
  use pretty_assertions::assert_eq;

  let one: Attribute = serde_yml::from_str("
    doc-ref: one element
  ").unwrap();
  assert_eq!(one, Attribute {
    doc: Doc {
      doc: None,
      doc_ref: Some(DocRef::One("one element".to_owned())),
    },
    ..Default::default()
  });

  let arr: Attribute = serde_yml::from_str("
    doc-ref:
      - 1st element
      - 2nd element
  ").unwrap();
  assert_eq!(arr, Attribute {
    doc: Doc {
      doc: None,
      doc_ref: Some(DocRef::Vec(vec![
        "1st element".to_owned(),
        "2nd element".to_owned(),
      ])),
    },
    ..Default::default()
  });
}
