name: Build & Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ksc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  ksc-compatible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose --features compatible
    - name: Run tests
      run: cargo test --verbose --features compatible
